version: "3"

services:
  frontend:
    build:
      context: ./frontend
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # depends_on:
    #   - backend

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: node-backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
