name: Deploy Angular to GitHub Pages and Vercel

on:
  push:
    branches:
      - main

jobs:
  # -------------------------------
  # Deploy to GitHub Pages
  # -------------------------------
  deploy-gh-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for GitHub Pages
        run: npm run build -- --configuration production --base-href /gallery-app/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist/frontend/browser
          token: ${{ secrets.GITHUB_TOKEN }}

  # -------------------------------
  # Deploy to Vercel by Git actions
  # -------------------------------
  deploy-vercel:
    runs-on: ubuntu-latest
    needs: deploy-gh-pages
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Vercel
        run: npm run build -- --configuration production --base-href /

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
