name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment on push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  # Set working directory to frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --configuration production --base-href /gallery-app/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages       # Target branch for deployment
        folder: frontend/dist/frontend/browser  # <-- only browser folder
        token: ${{ secrets.GITHUB_TOKEN }}