name: Deploy Angular to GitHub Pages and Vercel

on:
  push:
    branches:
      - main

jobs:
  # === Job 1: Deploy GitHub Pages ===
  deploy-gh-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project for GitHub Pages
        run: npm run build -- --configuration production --base-href /gallery-app/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist/frontend/browser
          token: ${{ secrets.GITHUB_TOKEN }}

  # === Job 2: Deploy Vercel ===
  deploy-vercel:
    runs-on: ubuntu-latest
    needs: deploy-gh-pages # chạy sau khi job trên xong (có thể bỏ nếu muốn chạy song song)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}       # lấy trong Vercel → Settings → Tokens
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}     # lấy trong .vercel/project.json
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
